anime4k:
  anime4k_path: %USERPROFILE%\AppData\Local\video2x\anime4k\Anime4K.jar
  java_path: C:\Program Files\Java\jdk-12.0.2\bin\java.exe
  path: %USERPROFILE%\AppData\Local\video2x\anime4k\Anime4K.jar
ffmpeg:
  ffmpeg_path: %USERPROFILE%\AppData\Local\video2x\ffmpeg-latest-win64-static\bin
  frames_to_video:
    -hwaccel: auto
    -y: true
    input_options:
      -f: image2
      -qscale:a: null
      -qscale:v: null
    output_options:
      -b:v: null
      -crf: 17
      -pix_fmt: null
      -vcodec: libx264
  migrating_tracks:
    -hwaccel: auto
    -y: true
    output_options:
      -c: copy
      -map:
      - 0:v?
      - 1:a?
      - 1:s?
      - 1:d?
      - 1:t?
      -pix_fmt: null
  video_to_frames:
    -hwaccel: auto
    -y: true
    output_options:
      -pix_fmt: rgba64be
      -qscale:v: null
video2x:
  image_format: png
  preserve_frames: false
  video2x_cache_directory: null
waifu2x_caffe:
  batch_size: 1
  crop_h: null
  crop_size: 128
  crop_w: null
  gpu: 0
  input_extention_list: null
  input_path: null
  mode: noise_scale
  model_dir: null
  noise_level: 3
  output_depth: 8
  output_extention: null
  output_path: null
  output_quality: -1
  path: %USERPROFILE%\AppData\Local\video2x\waifu2x-caffe\waifu2x-caffe-cui
  process: gpu
  scale_height: null
  scale_ratio: null
  scale_width: null
  tta: 0
  waifu2x_caffe_path: %USERPROFILE%\AppData\Local\video2x\waifu2x-caffe\waifu2x-caffe-cui.exe
waifu2x_converter:
  block-size: null
  disable-gpu: null
  force-OpenCL: null
  image-quality: null
  input: null
  jobs: null
  mode: noise-scale
  model-dir: null
  noise-level: 3
  output: null
  output-format: null
  path: %USERPROFILE%\AppData\Local\video2x\waifu2x-converter-cpp
  png-compression: null
  processor: null
  scale-ratio: null
  silent: true
  waifu2x_converter_path: %USERPROFILE%\AppData\Local\video2x\waifu2x-converter-cpp
waifu2x_ncnn_vulkan:
  g: 0
  i: null
  j: '1:2:2'
  m: models-cunet
  n: 2
  o: null
  path: %USERPROFILE%\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan
  s: 2
  t: 400
  v: null
  waifu2x_ncnn_vulkan_path: %USERPROFILE%\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan.exe
